// ELEVA i18n v2.0
window.ELEVA_T = {
  'ja':{
    home:'ホーム',generate:'生成',trend:'SNSトレンド',history:'履歴',add_video:'動画を追加',settings:'設定',admin:'管理者',logout:'ログアウト',dashboard:'ダッシュボード',credits:'クレジット',plan_upgrade:'プランをアップグレード',generate_btn:'動画を生成',generating:'AI生成中...',background_notice:'他のページに移動しても生成は続きます',completed:'動画が完成しました！',view_now:'今すぐ見る',split_title:'分割投稿の提案',optimize_prompt:'プロンプトを最適化',upload_material:'動画素材を選択（任意）',camera:'カメラ',photo:'写真',video:'動画',url:'URL',or_describe:'またはテキストで説明',url_placeholder:'動画・画像のURLを貼り付け',login:'ログイン',signup:'新規登録',email:'メールアドレス',password:'パスワード',save:'保存',cancel:'キャンセル',confirm:'確認',close:'閉じる',next:'次へ',back:'戻る',loading:'読み込み中...',error:'エラーが発生しました',success:'完了しました',best_post_times:'最適投稿時間',platform:'プラットフォーム',genre:'ジャンル',best_days:'最適曜日',best_time:'最適時間',sns_trend:'SNSトレンド',hashtags:'ハッシュタグ',music:'音楽',topics:'トピック',daily:'日次',weekly:'週次',monthly:'月次',chatbot_title:'ELEVA サポート',chatbot_welcome:'こんにちは！ELEVAサポートです。お気軽にご質問ください。',chatbot_placeholder:'メッセージを入力...',quick_reply_1:'料金プランは？',quick_reply_2:'動画の作り方',quick_reply_3:'解約方法',push_title:'生成完了をプッシュ通知でお知らせします',push_allow:'許可する',push_later:'あとで',push_completed:'動画の生成が完了しました！',hero_title:'AIが動画を作り、アルゴリズムが届ける。',hero_sub:'SNS投稿を、もっと賢く、もっとお手軽に。',start_free:'無料で試す',free_trial:'2週間無料 • クレジットカード不要',step1_title:'テキストまたは素材をアップロード',step2_title:'AIが4K動画に自動最適化',step3_title:'SNSへの投稿をサポート',plan_quiz_title:'あなたに最適なプランを診断する',quiz_q1:'目的は？',quiz_q1_a:'個人',quiz_q1_b:'ビジネス',quiz_q2:'主なSNSは？',quiz_q3:'投稿頻度は？',quiz_q3_a:'毎日',quiz_q3_b:'週3〜5',quiz_q3_c:'週1〜2',start_now:'今すぐ始める',payment_method:'お支払い方法',subscribe:'決済へ進む',consent_title:'定期購読について',consent_agree:'同意して支払いへ進む',welcome_to_eleva:'ELEVAへようこそ',your_purpose:'SNS活用の目的は？',personal_sns:'👤 個人SNS運用',business_pr:'🏪 お店PR・商品販売',target_platforms:'メインで使うSNSは？',select_genres:'コンテンツのジャンルを選択',follower_count:'現在のフォロワー数',posting_habits:'投稿頻度と経験',posting_frequency:'投稿頻度',experience_level:'SNS運用経験',select_lang:'言語を選択'
  },
  'en-us':{
    home:'Home',generate:'Generate',trend:'Trends',history:'History',add_video:'Add Video',settings:'Settings',admin:'Admin',logout:'Logout',dashboard:'Dashboard',credits:'Credits',plan_upgrade:'Upgrade Plan',generate_btn:'Generate Video',generating:'AI Generating...',background_notice:'You can navigate away — generation continues',completed:'Your video is ready!',view_now:'View Now',split_title:'Split Post Suggestion',optimize_prompt:'Optimize Prompt',upload_material:'Select Media (Optional)',camera:'Camera',photo:'Photo',video:'Video',url:'URL',or_describe:'Or describe in text',url_placeholder:'Paste video or image URL',login:'Login',signup:'Sign Up',email:'Email',password:'Password',save:'Save',cancel:'Cancel',confirm:'Confirm',close:'Close',next:'Next',back:'Back',loading:'Loading...',error:'An error occurred',success:'Completed',best_post_times:'Best Post Times',platform:'Platform',genre:'Genre',best_days:'Best Days',best_time:'Best Time',sns_trend:'SNS Trends',hashtags:'Hashtags',music:'Music',topics:'Topics',daily:'Daily',weekly:'Weekly',monthly:'Monthly',chatbot_title:'ELEVA Support',chatbot_welcome:'Hi! I\'m ELEVA Support. How can I help?',chatbot_placeholder:'Type a message...',quick_reply_1:'Pricing plans?',quick_reply_2:'How to create video',quick_reply_3:'How to cancel',push_title:'Get notified when your video is ready',push_allow:'Allow',push_later:'Later',push_completed:'Your video is complete!',hero_title:'Create. Optimize. Go Viral.',hero_sub:'Smarter, easier social media — powered by 4K AI video.',start_free:'Start Free',free_trial:'2-week free trial • No credit card required',step1_title:'Enter text or upload media',step2_title:'AI auto-optimizes to 4K video',step3_title:'Supports your social media posting',plan_quiz_title:'Find Your Perfect Plan',quiz_q1:'What\'s your goal?',quiz_q1_a:'Personal',quiz_q1_b:'Business',quiz_q2:'Which platform?',quiz_q3:'How often do you post?',quiz_q3_a:'Daily',quiz_q3_b:'3-5x/week',quiz_q3_c:'1-2x/week',start_now:'Get Started Now',payment_method:'Payment Method',subscribe:'Proceed to Payment',consent_title:'Subscription Details',consent_agree:'Agree & Proceed',welcome_to_eleva:'Welcome to ELEVA',your_purpose:'What is your SNS goal?',personal_sns:'👤 Personal SNS',business_pr:'🏪 Business / Products',target_platforms:'Which platforms?',select_genres:'Select content genres',follower_count:'Current follower count',posting_habits:'Posting habits',posting_frequency:'Posting frequency',experience_level:'Experience level',select_lang:'Select Language'
  },
  'ko':{
    home:'홈',generate:'생성',trend:'트렌드',history:'기록',add_video:'동영상 추가',settings:'설정',admin:'관리자',logout:'로그아웃',dashboard:'대시보드',credits:'크레딧',plan_upgrade:'플랜 업그레이드',generate_btn:'동영상 생성',generating:'AI 생성 중...',background_notice:'다른 페이지로 이동해도 생성이 계속됩니다',completed:'동영상이 완성되었습니다!',view_now:'지금 보기',split_title:'분할 게시 제안',optimize_prompt:'프롬프트 최적화',upload_material:'미디어 선택 (선택사항)',camera:'카메라',photo:'사진',video:'동영상',url:'URL',or_describe:'또는 텍스트로 설명',url_placeholder:'동영상 또는 이미지 URL 붙여넣기',login:'로그인',signup:'회원가입',email:'이메일',password:'비밀번호',save:'저장',cancel:'취소',confirm:'확인',close:'닫기',next:'다음',back:'뒤로',loading:'로딩 중...',error:'오류가 발생했습니다',success:'완료되었습니다',best_post_times:'최적 게시 시간',platform:'플랫폼',genre:'장르',best_days:'최적 요일',best_time:'최적 시간',sns_trend:'SNS 트렌드',hashtags:'해시태그',music:'음악',topics:'토픽',daily:'일별',weekly:'주별',monthly:'월별',chatbot_title:'ELEVA 지원',chatbot_welcome:'안녕하세요! ELEVA 지원입니다. 무엇을 도와드릴까요?',chatbot_placeholder:'메시지 입력...',quick_reply_1:'요금제는?',quick_reply_2:'동영상 만들기',quick_reply_3:'해지 방법',push_allow:'허용',push_later:'나중에',push_completed:'동영상 생성이 완료되었습니다!',hero_title:'만들고. 최적화하고. 바이럴하라.',hero_sub:'AI 4K 동영상으로 더 스마트한 SNS 운영.',start_free:'무료로 시작',start_now:'지금 시작하기',select_lang:'언어 선택',best_post_times:'최적 게시 시간',platform:'플랫폼',genre:'장르',best_days:'최적 요일',best_time:'최적 시간'
  },
  'zh-tw':{
    home:'首頁',generate:'生成',trend:'趨勢',history:'歷史',add_video:'新增影片',settings:'設定',admin:'管理',logout:'登出',dashboard:'儀表板',credits:'點數',plan_upgrade:'升級方案',generate_btn:'生成影片',generating:'AI 生成中...',background_notice:'可以切換頁面，生成將在背景繼續',completed:'影片已完成！',view_now:'立即查看',split_title:'分割發布建議',optimize_prompt:'最佳化提示詞',camera:'相機',photo:'照片',video:'影片',url:'URL',login:'登入',signup:'註冊',save:'儲存',cancel:'取消',next:'下一步',back:'返回',loading:'載入中...',chatbot_title:'ELEVA 支援',chatbot_placeholder:'輸入訊息...',quick_reply_1:'收費方案？',quick_reply_2:'如何製作影片',quick_reply_3:'如何取消訂閱',push_allow:'允許',push_later:'稍後',hero_title:'創作。優化。爆紅。',hero_sub:'AI 4K 影片，讓社群媒體更聰明更輕鬆。',start_free:'免費試用',start_now:'立即開始',select_lang:'選擇語言',best_post_times:'最佳發文時間',platform:'平台',genre:'類型',best_days:'最佳天數',best_time:'最佳時間',sns_trend:'SNS 趨勢',hashtags:'主題標籤',music:'音樂',topics:'話題',daily:'每日',weekly:'每週',monthly:'每月'
  },
  'zh-cn':{
    home:'首页',generate:'生成',trend:'趋势',history:'历史',add_video:'添加视频',settings:'设置',admin:'管理',logout:'退出登录',dashboard:'仪表板',credits:'积分',plan_upgrade:'升级方案',generate_btn:'生成视频',generating:'AI 生成中...',background_notice:'可以切换页面，生成将在后台继续',completed:'视频已完成！',view_now:'立即查看',split_title:'分割发布建议',optimize_prompt:'优化提示词',camera:'相机',photo:'照片',video:'视频',url:'URL',login:'登录',signup:'注册',save:'保存',cancel:'取消',next:'下一步',back:'返回',loading:'加载中...',chatbot_title:'ELEVA 支持',chatbot_placeholder:'输入消息...',quick_reply_1:'收费方案？',quick_reply_2:'如何制作视频',quick_reply_3:'如何取消订阅',push_allow:'允许',push_later:'稍后',hero_title:'创作。优化。爆红。',hero_sub:'AI 4K 视频，让社交媒体更智能更轻松。',start_free:'免费试用',start_now:'立即开始',select_lang:'选择语言',best_post_times:'最佳发文时间',platform:'平台',genre:'类型',best_days:'最佳天数',best_time:'最佳时间',sns_trend:'SNS 趋势',hashtags:'话题标签',music:'音乐',topics:'话题',daily:'日',weekly:'周',monthly:'月'
  },
  'de':{
    home:'Start',generate:'Erstellen',trend:'Trends',history:'Verlauf',add_video:'Video hinzufügen',settings:'Einstellungen',admin:'Admin',logout:'Abmelden',dashboard:'Dashboard',credits:'Guthaben',plan_upgrade:'Plan upgraden',generate_btn:'Video generieren',generating:'KI generiert...',background_notice:'Seite wechseln – Generierung läuft weiter',completed:'Ihr Video ist fertig!',view_now:'Jetzt ansehen',split_title:'Geteilter Beitrag',optimize_prompt:'Prompt optimieren',camera:'Kamera',photo:'Foto',video:'Video',url:'URL',login:'Anmelden',signup:'Registrieren',save:'Speichern',cancel:'Abbrechen',next:'Weiter',back:'Zurück',loading:'Laden...',chatbot_title:'ELEVA Support',chatbot_placeholder:'Nachricht eingeben...',push_allow:'Erlauben',push_later:'Später',hero_title:'Erstellen. Optimieren. Viral gehen.',hero_sub:'Intelligentere Social Media mit KI 4K Video.',start_free:'Kostenlos starten',start_now:'Jetzt starten',select_lang:'Sprache wählen',best_post_times:'Beste Posting-Zeiten',platform:'Plattform',genre:'Genre',best_days:'Beste Tage',best_time:'Beste Zeit',sns_trend:'SNS Trends',hashtags:'Hashtags',music:'Musik',topics:'Themen',daily:'Täglich',weekly:'Wöchentlich',monthly:'Monatlich'
  },
  'fr':{
    home:'Accueil',generate:'Générer',trend:'Tendances',history:'Historique',add_video:'Ajouter vidéo',settings:'Paramètres',admin:'Admin',logout:'Déconnexion',dashboard:'Tableau de bord',credits:'Crédits',plan_upgrade:'Mettre à niveau',generate_btn:'Générer la vidéo',generating:'Génération IA...',background_notice:'Vous pouvez naviguer — génération en arrière-plan',completed:'Votre vidéo est prête !',view_now:'Voir maintenant',split_title:'Publication divisée',optimize_prompt:'Optimiser le prompt',camera:'Caméra',photo:'Photo',video:'Vidéo',url:'URL',login:'Connexion',signup:'S\'inscrire',save:'Enregistrer',cancel:'Annuler',next:'Suivant',back:'Retour',loading:'Chargement...',chatbot_title:'Support ELEVA',chatbot_placeholder:'Tapez un message...',push_allow:'Autoriser',push_later:'Plus tard',hero_title:'Créer. Optimiser. Devenir viral.',hero_sub:'Réseaux sociaux plus intelligents avec IA 4K.',start_free:'Commencer gratuitement',start_now:'Commencer maintenant',select_lang:'Choisir la langue',best_post_times:'Meilleurs horaires',platform:'Plateforme',genre:'Genre',best_days:'Meilleurs jours',best_time:'Meilleure heure',sns_trend:'Tendances SNS',hashtags:'Hashtags',music:'Musique',topics:'Sujets',daily:'Quotidien',weekly:'Hebdomadaire',monthly:'Mensuel'
  },
  'es':{
    home:'Inicio',generate:'Generar',trend:'Tendencias',history:'Historial',add_video:'Agregar video',settings:'Configuración',admin:'Admin',logout:'Cerrar sesión',dashboard:'Panel',credits:'Créditos',plan_upgrade:'Mejorar plan',generate_btn:'Generar video',generating:'Generando con IA...',background_notice:'Puedes navegar — la generación continúa',completed:'¡Tu video está listo!',view_now:'Ver ahora',split_title:'Publicación dividida',optimize_prompt:'Optimizar prompt',camera:'Cámara',photo:'Foto',video:'Video',url:'URL',login:'Iniciar sesión',signup:'Registrarse',save:'Guardar',cancel:'Cancelar',next:'Siguiente',back:'Atrás',loading:'Cargando...',chatbot_title:'Soporte ELEVA',chatbot_placeholder:'Escribe un mensaje...',push_allow:'Permitir',push_later:'Después',hero_title:'Crear. Optimizar. Hacerse viral.',hero_sub:'Redes sociales más inteligentes con IA 4K.',start_free:'Comenzar gratis',start_now:'Empezar ahora',select_lang:'Seleccionar idioma',best_post_times:'Mejores horarios',platform:'Plataforma',genre:'Género',best_days:'Mejores días',best_time:'Mejor hora',sns_trend:'Tendencias SNS',hashtags:'Hashtags',music:'Música',topics:'Temas',daily:'Diario',weekly:'Semanal',monthly:'Mensual'
  },
  'pt-br':{
    home:'Início',generate:'Gerar',trend:'Tendências',history:'Histórico',add_video:'Adicionar vídeo',settings:'Configurações',admin:'Admin',logout:'Sair',dashboard:'Painel',credits:'Créditos',plan_upgrade:'Atualizar plano',generate_btn:'Gerar vídeo',generating:'Gerando com IA...',background_notice:'Você pode navegar — geração continua em segundo plano',completed:'Seu vídeo está pronto!',view_now:'Ver agora',split_title:'Postagem dividida',optimize_prompt:'Otimizar prompt',camera:'Câmera',photo:'Foto',video:'Vídeo',url:'URL',login:'Entrar',signup:'Cadastrar',save:'Salvar',cancel:'Cancelar',next:'Próximo',back:'Voltar',loading:'Carregando...',chatbot_title:'Suporte ELEVA',chatbot_placeholder:'Digite uma mensagem...',push_allow:'Permitir',push_later:'Depois',hero_title:'Criar. Otimizar. Viralizar.',hero_sub:'Redes sociais mais inteligentes com IA 4K.',start_free:'Começar grátis',start_now:'Começar agora',select_lang:'Selecionar idioma',best_post_times:'Melhores horários',platform:'Plataforma',genre:'Gênero',best_days:'Melhores dias',best_time:'Melhor hora',sns_trend:'Tendências SNS',hashtags:'Hashtags',music:'Música',topics:'Tópicos',daily:'Diário',weekly:'Semanal',monthly:'Mensal'
  },
  'th':{home:'หน้าหลัก',generate:'สร้าง',trend:'เทรนด์',history:'ประวัติ',add_video:'เพิ่มวิดีโอ',settings:'การตั้งค่า',admin:'ผู้ดูแล',logout:'ออกจากระบบ',dashboard:'แดชบอร์ด',credits:'เครดิต',plan_upgrade:'อัปเกรดแผน',generate_btn:'สร้างวิดีโอ',generating:'AI กำลังสร้าง...',background_notice:'ไปหน้าอื่นได้ — การสร้างยังดำเนินต่อ',completed:'วิดีโอของคุณพร้อมแล้ว!',view_now:'ดูเดี๋ยวนี้',camera:'กล้อง',photo:'รูปภาพ',video:'วิดีโอ',url:'URL',login:'เข้าสู่ระบบ',signup:'ลงทะเบียน',save:'บันทึก',cancel:'ยกเลิก',next:'ถัดไป',back:'ย้อนกลับ',loading:'กำลังโหลด...',chatbot_title:'ELEVA ซัพพอร์ต',chatbot_placeholder:'พิมพ์ข้อความ...',push_allow:'อนุญาต',push_later:'ภายหลัง',start_free:'เริ่มฟรี',start_now:'เริ่มเลย',select_lang:'เลือกภาษา',best_post_times:'เวลาโพสต์ที่ดีที่สุด',platform:'แพลตฟอร์ม',genre:'ประเภท',best_days:'วันที่ดีที่สุด',best_time:'เวลาที่ดีที่สุด',sns_trend:'เทรนด์ SNS',hashtags:'แฮชแท็ก',music:'เพลง',topics:'หัวข้อ',daily:'รายวัน',weekly:'รายสัปดาห์',monthly:'รายเดือน'},
  'vi':{home:'Trang chủ',generate:'Tạo',trend:'Xu hướng',history:'Lịch sử',add_video:'Thêm video',settings:'Cài đặt',admin:'Quản trị',logout:'Đăng xuất',dashboard:'Bảng điều khiển',credits:'Tín dụng',plan_upgrade:'Nâng cấp gói',generate_btn:'Tạo video',generating:'AI đang tạo...',background_notice:'Bạn có thể chuyển trang — quá trình tạo tiếp tục',completed:'Video của bạn đã sẵn sàng!',view_now:'Xem ngay',camera:'Máy ảnh',photo:'Ảnh',video:'Video',url:'URL',login:'Đăng nhập',signup:'Đăng ký',save:'Lưu',cancel:'Hủy',next:'Tiếp',back:'Quay lại',loading:'Đang tải...',chatbot_title:'Hỗ trợ ELEVA',chatbot_placeholder:'Nhập tin nhắn...',push_allow:'Cho phép',push_later:'Để sau',start_free:'Bắt đầu miễn phí',start_now:'Bắt đầu ngay',select_lang:'Chọn ngôn ngữ',best_post_times:'Thời gian đăng tốt nhất',platform:'Nền tảng',genre:'Thể loại',best_days:'Ngày tốt nhất',best_time:'Giờ tốt nhất',sns_trend:'Xu hướng SNS',hashtags:'Hashtag',music:'Âm nhạc',topics:'Chủ đề',daily:'Hàng ngày',weekly:'Hàng tuần',monthly:'Hàng tháng'},
  'id':{home:'Beranda',generate:'Buat',trend:'Tren',history:'Riwayat',add_video:'Tambah Video',settings:'Pengaturan',admin:'Admin',logout:'Keluar',dashboard:'Dasbor',credits:'Kredit',plan_upgrade:'Tingkatkan Paket',generate_btn:'Buat Video',generating:'AI sedang membuat...',background_notice:'Anda dapat berpindah halaman — pembuatan terus berlanjut',completed:'Video Anda sudah siap!',view_now:'Lihat Sekarang',camera:'Kamera',photo:'Foto',video:'Video',url:'URL',login:'Masuk',signup:'Daftar',save:'Simpan',cancel:'Batal',next:'Berikutnya',back:'Kembali',loading:'Memuat...',chatbot_title:'Dukungan ELEVA',chatbot_placeholder:'Ketik pesan...',push_allow:'Izinkan',push_later:'Nanti',start_free:'Mulai Gratis',start_now:'Mulai Sekarang',select_lang:'Pilih Bahasa',best_post_times:'Waktu Posting Terbaik',platform:'Platform',genre:'Genre',best_days:'Hari Terbaik',best_time:'Waktu Terbaik',sns_trend:'Tren SNS',hashtags:'Tagar',music:'Musik',topics:'Topik',daily:'Harian',weekly:'Mingguan',monthly:'Bulanan'}
};

window.ELEVA_LANG_NAMES = {
  'ja':{native:'日本語',flag:'🇯🇵'},'en-us':{native:'English (US)',flag:'🇺🇸'},'en-gb':{native:'English (UK)',flag:'🇬🇧'},
  'ko':{native:'한국어',flag:'🇰🇷'},'zh-tw':{native:'繁體中文',flag:'🇹🇼'},'zh-cn':{native:'简体中文',flag:'🇨🇳'},
  'de':{native:'Deutsch',flag:'🇩🇪'},'fr':{native:'Français',flag:'🇫🇷'},'es':{native:'Español',flag:'🇪🇸'},
  'pt-br':{native:'Português (BR)',flag:'🇧🇷'},'th':{native:'ภาษาไทย',flag:'🇹🇭'},'vi':{native:'Tiếng Việt',flag:'🇻🇳'},
  'id':{native:'Bahasa Indonesia',flag:'🇮🇩'},'ar':{native:'العربية',flag:'🇸🇦'},'hi':{native:'हिन्दी',flag:'🇮🇳'},
  'ms':{native:'Bahasa Melayu',flag:'🇲🇾'},'tr':{native:'Türkçe',flag:'🇹🇷'},'ru':{native:'Русский',flag:'🇷🇺'},
  'nl':{native:'Nederlands',flag:'🇳🇱'},'it':{native:'Italiano',flag:'🇮🇹'},'pl':{native:'Polski',flag:'🇵🇱'}
};

window.elevaT = function(key, lang) {
  const T = window.ELEVA_T;
  lang = lang || localStorage.getItem('eleva_lang') || 'ja';
  return (T[lang]&&T[lang][key])||(T['en-us']&&T['en-us'][key])||(T['ja']&&T['ja'][key])||key;
};
